from sphinx.highlighting import PygmentsBridge
from pygments.formatters.latex import LatexFormatter

class CustomLatexFormatter(LatexFormatter):
    def __init__(self, **options):
        super(CustomLatexFormatter, self).__init__(**options)
        self.verboptions = r"formatcom=\scriptsize"

PygmentsBridge.latex_formatter = CustomLatexFormatter

###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Robert Mařík, Tomáš Kudláček'
bibtex_bibfiles = []
#comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2023, 2024'
exclude_patterns = [
    '**.ipynb_checkpoints', 
    '.DS_Store', 
    'Thumbs.db',
    '_build', 
    'reseni*', 
    'cviceni/cviceni14.md', 
    'README.md'
    ]
#execution_allow_errors = False
#execution_excludepatterns = []
#execution_in_temp = False
#execution_timeout = 30
extensions = [
    'sphinx_togglebutton',
    'sphinx_copybutton',
    'notfound.extension',    
    'myst_nb',
    #'jupyter_book',
    'sphinx_comments',
    'sphinx_external_toc',
    'sphinx.ext.intersphinx',
    'sphinx_design',
    'sphinx_book_theme',
    'sphinx_proof',
    #'sphinx_jupyterbook_latex'
#    'sphinx_last_updated_by_git',
]
#oznameni = """
#Toto jsou učební texty předmětu Matematika převedené do nové šablony. Stará verze je po nějaký čas k dispozici na  <a href="https://robert-marik.github.io/matematika-old">https://robert-marik.github.io/matematika-old</a> a nebude již udržována.
#"""
#extra_navbar = '<a href="https://user.mendelu.cz/marik/Matematika.pdf">Offline verze v PDF</a>'
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = ''
html_show_copyright = False
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {
    'extra_footer': '<p>\n<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>\n  All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>\n</p>',
    #'search_bar_text': 'Hledat v textu...',
    'path_to_docs': '',
    'repository_url': 'https://github.com/robert-marik/matematika',
    'repository_branch': 'main',
    'home_page_in_toc': False,
    'use_repository_button': False,
    'use_edit_page_button': False,
    'use_issues_button': False,
    'use_download_button': False,
    'use_fullscreen_button': False,
    #'announcement': oznameni,
    #"collapse_navigation": True,
    "navigation_with_keys": False,
}
html_title = 'Matematika'
html_sidebars = {
    "**": [
        "navbar-logo.html",
#        "offline-version.html",
        "search-field.html",
        "sbt-sidebar-nav.html",
    ]
}
#jupyter_cache = ''
#jupyter_execute_notebooks = 'auto'
latex_engine = 'xelatex'
myst_enable_extensions = ['amsmath', 'dollarmath']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
myst_dmath_double_inline = True

#html_css_files = ['custom.css']
language = 'cs'
myst_footnote_transition = False
latex_elements = {
    'extrapackages': r'\usepackage{comment}', 
    'papersize': 'a4paper',
    'preamble':r'\input custom_preamble.tex'
    }

html_js_files = [
    'custom.js',
#    'https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js'
]
#latex_table_style = ['booktabs']

#notfound_urls_prefix = '/matematika/'
#latex_toplevel_sectioning = 'chapter'

